# Author: Psycho0verload (29304143+Psycho0verload@users.noreply.github.com)
# dns_checks.yml (c) 2024
# Desc: Check the DNSControl configuration and preview the changes
# Created:  2024-05-31T20:41:19.509Z
# Modified: 2024-06-02T07:52:50.141Z
on:
  workflow_dispatch:
  push:
name: "⚙️ Checks"
jobs:
  check:
    name: "Check & Preview the DNSControl configuration"
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
    - uses: actions/checkout@v4
    - name: "Check the configuration"
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/stackexchange/dnscontrol:latest
        options: --rm -e HOSTINGDE_AUTH_TOKEN=${{ secrets.HOSTINGDE_AUTH_TOKEN }} -v ${{ github.workspace }}:/dns
        run: |
          dnscontrol check
    - name: "Preview of the DNS changes"
      uses: addnab/docker-run-action@v3
      with:
        image: ghcr.io/stackexchange/dnscontrol:latest
        options: --rm -e HOSTINGDE_AUTH_TOKEN=${{ secrets.HOSTINGDE_AUTH_TOKEN }} -v ${{ github.workspace }}:/dns
        run: |
          dnscontrol preview